default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: more_rails_routing_development

test:
  <<: *default
  database: more_rails_routing_test
